ALTER TABLE regulations  ADD COLUMN IF NOT EXISTS source_url  TEXT;
ALTER TABLE regulations  ADD COLUMN IF NOT EXISTS source_note TEXT;
ALTER TABLE requirements ADD COLUMN IF NOT EXISTS ref_verified BOOLEAN NOT NULL DEFAULT FALSE;
